
#pragma once

//generated by ErrorExport.js

#include "SourenaErrors.generated.h"

UENUM(BlueprintType)
enum class ESourenaRpcErrorCode : uint8
{
	//timeout
	SErrCode_Timeout = 3,
	//rpc is pending
	SErrCode_RpcIsPending = 4,
	//rate limit reached
	SErrCode_RateLimitReached = 5,
	//per rpc rate limit reached
	SErrCode_PerRPCRateLimitReached = 6,
	//method not found
	SErrCode_MethodNotFound = 7,
	//QueryFailed
	SErrCode_QueryFailed = 20,
	//no empty supervisor available
	SErrCode_NoEmptySupervisor = 21,
	//already logged in
	SErrCode_AlreadyLoggedIn = 22,
	//login failed
	SErrCode_LoginFailed = 23,
	//user is already joined to the lobby
	SErrCode_UserAlreadyJoined = 24,
	//invalid lobby
	SErrCode_InvalidLobby = 25,
	//lobby is closed
	SErrCode_LobbyIsClosed = 26,
	//lobby is locked
	SErrCode_LobbyIsLocked = 27,
	//lobby is full
	SErrCode_LobbyIsFull = 28,
	//lobby is already locked
	SErrCode_LobbyAlreadyLocked = 29,
	//you are banned from playing the game
	SErrCode_UserPlayBan = 30,
	//user not found
	SErrCode_UserNotFound = 31,
	//token sign failed
	SErrCode_TokenSignFailed = 32,
	//wrong password
	SErrCode_WrongPassword = 33,
	//u are not allowed to login
	SErrCode_LoginNotAllowed = 34,
	//build not found
	SErrCode_BuildNotFound = 35,
	//gamemode not found
	SErrCode_GameModeNotFound = 36,
	//lobby closed during JoinUser
	SErrCode_LobbyClosedDuringJoinUser = 37,
	//failed to sign token when joining user to the lobby
	SErrCode_JoinUserSignFailed = 38,
	//lobby not registered
	SErrCode_LobbyNotRegistered = 39,
	//lobby closed
	SErrCode_LobbyClosed = 40,
	//lobby unregistered
	SErrCode_LobbyUnregistered = 41,
	//lobby crashed
	SErrCode_LobbyCrashed = 42,
	//invalid token
	SErrCode_InvalidToken = 43,
	//lobby is already registered
	SErrCode_LobbyAlreadyRegistered = 44,
	//invalid player ticket
	SErrCode_InvalidPlayerTicket = 45,
	//user is not joined to the lobby
	SErrCode_JuserIsNotJoined = 46,
	//invalid user state
	SErrCode_InvalidUserState = 47,
	//someone else already logged in
	SErrCode_SomeoneElseAlreadyLogedIn = 48,
	//invalid json
	SErrCode_InvalidJSON = 100,
	//invalid params
	SErrCode_InvalidParams = 101,
	//invalid result
	SErrCode_InvalidResult = 102,
	//invalid id
	SErrCode_InvalidId = 103,
	//invalid method
	SErrCode_InvalidMethod = 104,
	//not confirmed
	SErrCode_NotConfirmed = 105,
	//not implemented yet
	SErrCode_NotImplementedYet = 106,
	//invalid access
	SErrCode_InvalidAccess = 107,
	//#TODO
	SErrCode_TODO = 108,
	//failed to generate hash
	SErrCode_FailedToGenHash = 109,
	//no empty port
	SErrCode_NoEmptyPort = 110,
	//supervisor not found
	SErrCode_SupervisorNotFound = 111,
	//connection already exists
	SErrCode_ConnectionExists = 112,
	//invalid connection
	SErrCode_InvalidConnection = 113,
	//register failed
	SErrCode_RegisterFailed = 114,
	//exception happened
	SErrCode_ExceptionHappend = 115,
	//invalid steam ticket
	SErrCode_InvalidSteamTicket = 116,
	//max call reached
	SErrCode_MaxCallReached = 117,
	//email or username exists
	SErrCode_EmailOrUsernameExists = 118,
	//username taken
	SErrCode_UsernameTaken = 119,
	//email taken
	SErrCode_EmailTaken = 120,
	//password too weak
	SErrCode_PasswordTooWeak = 121,
	//invalid username
	SErrCode_InvalidUsername = 122,
	//invalid email
	SErrCode_InvalidEmail = 123,
	//password not same
	SErrCode_PasswordNotSame = 124,
	//friend request pending
	SErrCode_FriendRequestPending = 125,
	//friend request blocked
	SErrCode_FriendRequestBlocked = 126,
	//friend request declined
	SErrCode_FriendRequestDeclined = 127,
	//friend request already accepted
	SErrCode_FriendRequestAlreadyAccepted = 128,
	//no such user is blocked
	SErrCode_NoSuchUserIsBlocked = 129,
	//max relationship reached
	SErrCode_MaxRelationshipReached = 130,
	//invalid flow
	SErrCode_InvalidFlow = 131,
	//invalid action
	SErrCode_InvalidAction = 132,
	//is blocked by other
	SErrCode_IsBlockedByOther = 133,
	//is declined by other
	SErrCode_IsDeclinedByOther = 134,
	//are not friend
	SErrCode_AreNotFriend = 135,
	//not found
	SErrCode_NotFound = 139,
	//not joined
	SErrCode_NotJoined = 140,
	//already joined
	SErrCode_AlreadyJoined = 141,
	//invalid ticket
	SErrCode_InvalidTicket = 142,
	//party is matchmaking
	SErrCode_PartyIsMatchmaking = 143,
	//queue not found
	SErrCode_QueueNotFound = 144,
	//match ticket not found
	SErrCode_MatchTicketNotFound = 145,
	//class not found
	SErrCode_ClassNotFound = 146,
	//party is full
	SErrCode_PartyIsFull = 147,

};
